# Introduction to NumPy

### first of all we need to import Numpy

In [1]:
import numpy

This imports NumPy into the currect workflow. You can accass NumPy not with numpy.X

In [2]:
numpy.__version__ # Nearly all packages have .__version__ 

'1.12.1'

However NumPy is so popular the whole world follows one conversion: to import NumPy always with a shortcut "as np"

In [3]:
import numpy as np

In [5]:
np.__version__

'1.12.1'

# So for what is NumPy good?

For fast matrix manipulations.

In [6]:
lst = [1, 2, 3, 4]
a = np.array(lst)

In [7]:
a

array([1, 2, 3, 4])

## Reminder: what is now different to a list? 

In [8]:
lst

[1, 2, 3, 4]

# Be careful

In [9]:
print(a)

[1 2 3 4]


# So better check the type

In [10]:
type(a)

numpy.ndarray

In [11]:
type(a) == np.ndarray

True

In [12]:
a.shape

(4,)

In [13]:
# its more like a list not a tuple
a[0] = -1 
a

array([-1,  2,  3,  4])

## Multi dimensionl arrays

In [33]:
lst = [[1, 2], [3, 4]]
a = np.array(lst)

In [34]:
a

array([[1, 2],
       [3, 4]])

In [35]:
a.shape

(2, 2)

In [36]:
type(a[0])

numpy.ndarray

In [37]:
a[1, 1]

4

In [38]:
a.T

array([[1, 3],
       [2, 4]])

In [39]:
a = np.zeros((2,2))
a

array([[ 0.,  0.],
       [ 0.,  0.]])

In [40]:
a = np.ones((2,2))
a

array([[ 1.,  1.],
       [ 1.,  1.]])

In [43]:
a = np.full((3,2), 300.0)
a

array([[ 300.,  300.],
       [ 300.,  300.],
       [ 300.,  300.]])

In [44]:
a = np.random.random((2,2))
a

array([[ 0.69064261,  0.32443766],
       [ 0.54020572,  0.32898246]])

In [45]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12] , [13,14,15,16]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [46]:
a[2,3] # [ROW, COLUMN] statring with 0

12

In [49]:
a[:,0] # First Column

array([ 1,  5,  9, 13])

In [51]:
a[   0   , : ]  #first row

array([1, 2, 3, 4])

In [52]:
a[1:-1, 1:-1] #the heart/core

array([[ 6,  7],
       [10, 11]])

In [53]:
a = np.array([[[1,2],[3,4]], [[5,6],[7,8]], [[9,10],[11,12]] , [[13,14],[15,16]]])
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]]])

In [54]:
a.shape

(4, 2, 2)

In [57]:
a[:, 1, 0]

array([ 3,  7, 11, 15])

# Operations

In [58]:
np.sum(a)

136

In [59]:
np.sum(a, axis=1)

array([[ 4,  6],
       [12, 14],
       [20, 22],
       [28, 30]])

# How to find out more about the function?
are there more parameter? Use the "?" after every function to find out the functions spesifications.

In [64]:
np.sum?

In [65]:
np.sum(a[:, 1, 0])

36

In [66]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

In [79]:
np.add(x,y)

array([[ 6,  8],
       [10, 12]])

In [80]:
x+y

array([[ 6,  8],
       [10, 12]])

In [74]:
x+v

array([[10, 12],
       [12, 14]])

In [75]:
y-x

array([[4, 4],
       [4, 4]])

In [70]:
y*x

array([[ 5, 12],
       [21, 32]])

In [81]:
y/w

array([[ 0.45454545,  0.5       ],
       [ 0.63636364,  0.66666667]])

In [82]:
np.sqrt(x)

array([[ 1.        ,  1.41421356],
       [ 1.73205081,  2.        ]])

In [83]:
np.sqrt(x)

array([[ 1.        ,  1.41421356],
       [ 1.73205081,  2.        ]])

In [84]:
print (v.dot(w))
print (np.dot(v, w))

219
219


In [85]:
print( x.dot(v))
print (np.dot(x, v))

[29 67]
[29 67]


In [86]:
print (x.dot(y))
print (np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


# Filter & Replace

In [87]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12] , [13,14,15,16]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [92]:
a[a > 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [100]:
a[(a > 5) & (a < 10)]

array([6, 7, 8, 9])

In [101]:
a[2,:]  = [99,88,77,66]
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [99, 88, 77, 66],
       [13, 14, 15, 16]])

In [49]:
a[:,2]  = [55,44,33,22]
a

array([[ 1,  2, 55,  4],
       [ 5,  6, 44,  8],
       [99, 88, 33, 66],
       [13, 14, 22, 16]])

In [103]:
a.reshape(16)

array([ 1,  2,  3,  4,  5,  6,  7,  8, 99, 88, 77, 66, 13, 14, 15, 16])

In [104]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8, 99, 88, 77, 66, 13, 14, 15, 16])

In [105]:
a.reshape((2, 8))

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [99, 88, 77, 66, 13, 14, 15, 16]])

# Types

In [106]:
a.astype(float) 

array([[  1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.],
       [ 99.,  88.,  77.,  66.],
       [ 13.,  14.,  15.,  16.]])

In [108]:
a + 0.0

array([[  1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.],
       [ 99.,  88.,  77.,  66.],
       [ 13.,  14.,  15.,  16.]])

In [109]:
a + 0.1

array([[  1.1,   2.1,   3.1,   4.1],
       [  5.1,   6.1,   7.1,   8.1],
       [ 99.1,  88.1,  77.1,  66.1],
       [ 13.1,  14.1,  15.1,  16.1]])

In [110]:
(a + 0.7).astype(int)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [99, 88, 77, 66],
       [13, 14, 15, 16]])

In [112]:
np.round(a + 0.7).astype(int)

array([[  2,   3,   4,   5],
       [  6,   7,   8,   9],
       [100,  89,  78,  67],
       [ 14,  15,  16,  17]])